version: '3'

services: 

  db:
    image: mysql:5.7
    platform: linux/x86_64
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"] 
      interval: 5s
      timeout: 10s
      retries: 3

  app:
    build:
      context: node
    container_name: app
    command: ["node", "index.js"]
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    
    

networks:
  node-network:
    driver: bridge